version: '3'
services:
    mysql:
       image: mysql:latest
       restart: always
       environment:
         - MYSQL_ROOT_PASSWORD=mysql
       ports:
         - "3306:3306"
       volumes:
         - mysqldata:/var/lib/mysql
    
    
    postgres:
       image: postgres:latest
       environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgress
         - POSTGRES_DB=postgres
       ports:
         - "5432:5432"
       volumes:
         - "pgdata:/var/lib/postgresql/data"
    
    mssql:
       image: microsoft/mssql-server-linux
       environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Secret1234
       ports:
         - "1433:1433"
       volumes:
         - "msdata:/var/lib/mssql/data"
    

volumes:
    mysqldata:
    pgdata:
    msdata: