version: '3'
services:
    mysql:
       image: mysql:latest
       restart: always
       environment:
         - MYSQL_ROOT_PASSWORD=mysql
       ports:
         - "3306:3306"
       volumes:
         - mysqldata:/var/lib/mysql

    userserver:
       build:
        context: .
        dockerfile: Dockerfile
       image: userserver:2.0.0
       environment:
        - HTTP_PORT=8080
        - MYSQL_HOST=mysql
        - DB_DRIVER=mysql
       ports:
        - "8080:8080"
       depends_on:
        - mysql
volumes:
    mysqldata: