version: '3'
services:
    postgres:
       image: postgres:latest
       environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgress
         - POSTGRES_DB=postgres
       ports:
         - "5432:5432"
       volumes:
         - "pgdata:/var/lib/postgresql/data"

    userserver:
       build:
        context: .
        dockerfile: Dockerfile
       image: userserver:2.0.0
       environment:
        - DB_DRIVER=postgres
        - HTTP_PORT=8080
        - PG_HOST=postgres
       ports:
        - "8080:8080"
       depends_on:
        - postgres
volumes:
    pgdata:
