{
	"db_driver": "mysql",
    "mssql":	{
					"pro_db": {
                        			"host": "localhost",
                        			"port": 1433,
                        			"user": "sa",
                        			"pass": "Secret1234",
                        			"dbname":"fuf_demo"
                					},
					"test_db":{
                        			"host": "localhost",
                        			"port": 1433,
                        			"user": "sa",
                        			"pass": "Secret1234",
                        			"dbname":"fuf_demo"
                					},
			},
	"postgres": {	
					"pro_db": {	
								"host": "localhost",
								"port":	5432,
								"user":	"postgres",
								"pass":	"postgress",
								"dbname":"fuf_demo"
							},
					"test_db": {
								"host": "localhost",
				                 "port": 5432,
				                 "user": "postgres",
				                 "pass": "postgress",
				                 "dbname":"fuf_test"
						 }
				},
	"mysql": {	
					"pro_db": {	
								"host": "localhost",
								"port":	3306,
								"user":	"root",
								"pass":	"mysql",
								"dbname":"fuf_demo"
							},
					"test_db": {
								"host": "localhost",
				                 "port": 3306,
				                 "user": "root",
				                 "pass": "mysql",
				                 "dbname":"fuf_test"
						 }
				}			
}
